### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Relintai** [Homebrodot/platform-switch#1]
As the title says, there is no license in the repository. Since law (and copyright law) is already a mess, and just based on the few stories I heard about Nintendo, it'd be probably better to have one.

Libnx seems to have one that's reasonable, but I don't have proper knowledge of the homebrew scene, so there might be way better licenses:

https://github.com/switchbrew/libnx?tab=ISC-1-ov-file

**Comment by halotroop2288** [comment]
It's intended to retain the MIT license (with credit to our team) as stated in the file headers.
